language: python
python:
  - "2.7"
  - "3.6"
  - "nightly"
  - "pypy"
  - "pypy3"
install:
  - pip install -r requirements.txt
script: for f in examples/* ; do python bin/8080.py "$f" ; done; rm "examples/$f.rom"
